### ISSUE TITLE
FNT Weather received but not shown in Received list

### ISSUE THREAD

**Issue by mreinart** [gereic/GXAirCom#114]
Recent Version 5.0.0 - freshly built
SIM7000G module with LoRa-Chip receives FNT sentences from nearby FANET Weatherstation (Skytraxx)
Log shows lines
#FNF 1,11D,1,0,4,D,7626004696F40511E4202EBB0F
#FNF 1,11D,1,0,8,5,0165026026
this FANET ID is shown in List for 'Send message' but the weather data are not shown in Received Weatherstation data list on WebUI - or only much later
The SykTraxx Weatherstation is well received on a nearby SkyTraxx flight computer
- working on one SIM7000G module but note on the first one
- similar configuration as Groundstation/Weatherstation

**Comment by gereic** [comment]
Can you try to build with latest source fromm master-branch ?

**Comment by mreinart** [comment]
was a 'hanging' effect - refreshed later
