### ISSUE TITLE
DT in MQTT data - UTC timezone indicator

### ISSUE THREAD

**Issue by mreinart** [gereic/GXAirCom#117]
It would be beneficial if the date/time string in the MQTT data would clearly indicate the UTC reference.

e.g.: DT: "2022-12-27 21:03:03" 
-> "2022-12-27T21:03:03+00:00"  [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html)

**Comment by gereic** [comment]
Fixed it in V5.2.0
Just update the firmware, or restart the board and the update will bei automatically loaded.

**Comment by mreinart** [comment]
working fine
