### ISSUE TITLE
Case for pigtail anteanna connectors

### ISSUE THREAD

**Issue by bzed** [gereic/GXAirCom#12]
Based on your case I've created a case version for an antenna connection using a pigtail, which is shipped with some of the t-beam models (like the one I have here with the M8N ublox module).

Feel free to use/integrate it - or if not please provide your own version of such a case.
I'm using openscad because thats what I know :+1: 

Files are here:
https://shell.bzed.at/~bzed/.publish/2020-11-24-pSoA3siqqOY/

**Comment by gereic** [comment]
Thank you, I will put it on the github
