### ISSUE TITLE
message menu missing

### ISSUE THREAD

**Issue by Gandalfderweisze** [gereic/GXAirCom#122]
Just updated to 5.3.0 and found out that the message menu is missing unter 192.168.4.1. Could not find a checkbox or similar to switch it on again....

greetings
Jürgen

**Comment by gereic** [comment]
This menu-point was only for testing and I thought nobody need it.
If you really need it, I can put it in, and show it, when expert-view is choosen in settings.
Is that ok ?

**Comment by Gandalfderweisze** [comment]
Hello, that would be perfect!ThanksJürgen--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.02.23, 08:07 schrieb gereic ***@***.***>:

   
  This menu-point was only for testing and I thought nobody need it. If you really need it, I can put it in, and show it, when expert-view is choosen in settings. Is that ok ?

**Comment by gereic** [comment]
included in V5.3.1

**Comment by Gandalfderweisze** [comment]
Thank's! Installed and working!
