### ISSUE TITLE
FANET

### ISSUE THREAD

**Issue by cloudsun9** [gereic/GXAirCom#14]
I have two T-Beams for testing.
The T-Beams with GXAirCom installed can see each other, but while my Skytraxx 2.1 can see both T-Beams they cannot see the Skytraxx.
I cannot find a setting to fix this, so is it a firmware issue?

**Comment by nepat** [comment]
The Skytraxx 2.1 will only start sending FANET position data once the Skytraxx is in motion (flying). You can force the Skytraxx to send position data over FANET in a stationary position by changing the 'Recorder' setting from 'Auto' to 'On'.
