### ISSUE TITLE
Migration to SparkFun u-blox Arduino GNSS Library v2.2.24

### ISSUE THREAD

**Issue by VirusPilot** [gereic/GXAirCom#142]
Some of us are now seriously working on the u-blox configuration code, therefore and particularly for the M10S on the T-Beam S3 Core board it would be beneficial if the SparkFun u-blox library could be updated to the latest version 2.2.24 as it offers full support for generation 8, 9 and 10 u-blox GNSS modules, see here:

http://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#compatibility

Migration is pretty simple, see here:

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#migrating-to-v20

I am already successfully using this library in my fork.

EDIT: links corrected

**Comment by gereic** [comment]
Added in latest version

**Comment by rvt** [comment]
Sweet, I will modify my code to use this lib aswell
