### ISSUE TITLE
[Feature Request] Add Bluetooth SPP

### ISSUE THREAD

**Issue by parapenT1sta** [gereic/GXAirCom#147]
Due issues I have with my phone LE bluetooth with some devices using LE BT. Is it possible to add the option for Bluetooth SPP?

For example, running SoftRF on my phone with Bluetooth LE I have a lot of disconnections but running with Bluetooth SPP I have no issues at all.

I'm requesting this for better compatibility with some older devices.

**Comment by parapenT1sta** [comment]
@gereic @rvt Is it possible to add it? In my case would help a lot.

**Comment by gereic** [comment]
Sorry,
the space on device is not enough to implement this feature again.
