### ISSUE TITLE
Bug: XCGuide + Firmware nopsRam Version 5.5

### ISSUE THREAD

**Issue by AHausBy** [gereic/GXAirCom#156]
Bluetooth  Connection Issue, when XCGuide trying to connect to Heltec Board. GXAircom is restarting all the time.

**Comment by gereic** [comment]
Should be fixed in v5.5.1

**Comment by AHausBy** [comment]
Could you please provide also spiffs_v5.5.1.bin in bin folder 😬

**Comment by gereic** [comment]
sorry,
Did it. ;-)

**Comment by AHausBy** [comment]
Fine thx runs stable now with XCGuide and v5.5.1

**Comment by AHausBy** [comment]
Closed issue
