### ISSUE TITLE
.bin filenames

### ISSUE THREAD

**Issue by cloudsun9** [gereic/GXAirCom#24]
With V4.x.x I do not understand the .bin file names any more.
Is there a way to decipher them?

**Comment by nepat** [comment]
With V4.x.x the number of versions has been reduced.
sim7000 is for the Lilygo ttgo t-sim7000g
sim800 is for boards connected to a sim800 gprs modem
psRam is for boards with PSRam (the Lilygo t-beam series)
nopsRam is for all the rest (Heltec and Lilygo LoRa boards - except for the Lilygo t-beam series)
