### ISSUE TITLE
FANET Aircraft shown with name of received weather station

### ISSUE THREAD

**Issue by mreinart** [gereic/GXAirCom#27]
Hello Gerald,
great work - I really like it.

Trying with build 4.3.1 (binary download). I am operating a local Skytraxx FANET Windstation with ID `01:011D` and name "`wGer`" and also turned on Skytraxx 2.1 with ID: `11:2BBB`, name "`MaRe`". 
(See attached.)

On '/neighbours.html' the SkyTraxx 2.1 is shown with the name of the Windstation.
Investigating further my self.

Kind Regards
Manfred
--
![Screenshot 2021-02-08 at 12 57 42](https://user-images.githubusercontent.com/2735323/107217128-04f23280-6a0e-11eb-8567-240f9db16693.png)
![Screenshot 2021-02-08 at 12 57 08](https://user-images.githubusercontent.com/2735323/107217140-0ae81380-6a0e-11eb-90d6-070475a7a7aa.png)

**Comment by gereic** [comment]
Found a Bug.
Can you upgrade to Version v4.3.2 please.
