### ISSUE TITLE
set FANET status "landed ok" after landing and pilot confirmation

### ISSUE THREAD

**Issue by rrunner83** [gereic/GXAirCom#33]
i as a user should be asked after landing, if the landing was ok and everything is fine
AND can confirm this message by pressing a hardware button on the device (on ttgo beam v1.1 - IO38)
THEN the fanet status "landed ok" will be set automatically

(this feature is a "copy" of the handling in skytraxx fanet instruments)

**Comment by gereic** [comment]
Fixed in Version 4.11
