### ISSUE TITLE
TTGO platform IO error 

### ISSUE THREAD

**Issue by parahooners** [gereic/GXAirCom#44]
![received_219614299907166](https://user-images.githubusercontent.com/73525787/112537023-19b03d00-8da6-11eb-8cbf-bfaf33566e1d.jpeg)
 
Hey, can any one assist getting this error after flashing

**Comment by parahooners** [comment]
@gereic

**Comment by gereic** [comment]
BMPM085 is not supported yet ?
Is this your own code ?

**Comment by gereic** [comment]
I think you didn't downloaded the code.
Looks like a testprogram for a BMP085

**Comment by parahooners** [comment]
https://user-images.githubusercontent.com/73525787/112540976-bbd22400-8daa-11eb-96a4-7b121d8ed809.mp4

Uploaded the code directly from the code link getting this ....

@gereic  not my own firmware straight from the github page

**Comment by gereic** [comment]
This is not GXAircom, cause the size is 21.9% and that is much too less.
Don't know which software you try to compile, but this is not GxAircom.
You can download the software directly with ESP32 tools, that is easyer for beginners.
