### ISSUE TITLE
Not building Web-Helper Issue

### ISSUE THREAD

**Issue by parahooners** [gereic/GXAirCom#45]
Hello, @gereic 

When building the latest file vi Atom IO using platform IO the web page is not working when trying to access the board... what have I missed here

<img width="478" alt="Screenshot 2021-04-03 at 13 28 24" src="https://user-images.githubusercontent.com/73525787/113478454-d11d1180-9480-11eb-9592-e98396374186.png">

**Comment by gereic** [comment]
you have to create and upload also the filesystem-image.

**Comment by parahooners** [comment]
Sorted thank you
