### ISSUE TITLE
GPS coordinates are not updating in GS mode

### ISSUE THREAD

**Issue by bortek** [gereic/GXAirCom#48]
Testing GroundStation mode on T-beam v1.1.  

According to the PDF doc the coordinates should be automatically set using GPS if they are set to zeroes in the settings. But this does not seem to work. When checking i the INFO page after startup the coords are still zeroes.

Another issue is that the GS is not visible on the OGN network but the test aircraft is showing up. I can see other GS on the map but not mine.

I am using GXaircom v 4.7 from bin/dev directory in the repo.

**Comment by bortek** [comment]
![image](https://user-images.githubusercontent.com/9476606/115984965-f3024380-a5a9-11eb-802c-73b86f8bcd64.png)

**Comment by gereic** [comment]
When you set GXAircom to Ground-Station, you have to set GPS-coordinates in the settings-page.
It will not automatically used from GPS.
