### ISSUE TITLE
Flashing FW v4.6.1 does not work on T-beam v1.1

### ISSUE THREAD

**Issue by bortek** [gereic/GXAirCom#49]
I tried flashing firmware version 4.6.1 from the bin directory in this repo but it does not work after the restart. It loops in the GXAircoom logo and then restarts then loop continues.

Can anyone test and confirm?

![image](https://user-images.githubusercontent.com/9476606/115984473-8423eb00-a5a7-11eb-9b5a-a7a63a8778bd.png)

**Comment by gereic** [comment]
Can you try latest Version v4.7.0 please ?

**Comment by bortek** [comment]
Yes 4.7.0 works without any issues.
