### ISSUE TITLE
Version 4.8.5.

### ISSUE THREAD

**Issue by danielvelezbravo** [gereic/GXAirCom#50]
How did i get my hands on version 4.8.5?

I can´t find it anymore. I´m pretty sure i got it from dev. Now I see we are "down" to 4.7.1

**Comment by gereic** [comment]
Hi Daniel,



I removed it, cause it was only a dev-Version.

So actual Version is v4.7.0

Dev-Version is v4.7.1



-----Ursprüngliche Nachricht-----
Von: ***@***.***>
Gesendet: Montag 3 Mai 2021 21:34
An: gereic/GXAirCom ***@***.***>
CC: Subscribed ***@***.***>
Betreff: [gereic/GXAirCom] Version 4.8.5. (#50)


How did i get my hands on version 4.8.5?

I can´t find it anymore. I´m pretty sure i got it from dev. Now I see we are "down" to 4.7.1
