### ISSUE TITLE
baro altitude on XCSOAR (Kobo)

### ISSUE THREAD

**Issue by erwin4u-alt** [gereic/GXAirCom#54]
Hello,
I'm using an BMP280 on TTGO TBEAM with GXAirCom version 4.8.0 via UDP connected to an Kobo with XCSoar 
On the web-console I can see the pressure data but XCSOAR isn't able to interpret. I tried in LK8000 and it works fine. 
Would it possible to add the altitude data form the BMP in a XCSOAR readable format?
Cheers - Thomas

**Comment by gereic** [comment]
That's correct.
XCSoar is not able to read LK8EX1-String.
I will integrate the LXWP0-output, then it will work.
All you have to do is to set drive to LX.
Hope I can implement it this week.

**Comment by gereic** [comment]
New Version v4.9.0 is avaiable.
Just switch "output vario" to "LXWP0".
In XCSoar select LXNAV as device

**Comment by erwin4u-alt** [comment]
Many thanks to you -it works fine - great job!!!
