### ISSUE TITLE
GPS no fix - XC Guide

### ISSUE THREAD

**Issue by AHausBy** [gereic/GXAirCom#64]
Firmware:
firmware_v4.11.0_nopsRam.bin

Board:
Heltec

Connected Heltec Boad via Bluetooth with XCGuide.
Settings in XCGuide "Send GPS to Board" is set.

XCGuide Status GPS is ok 

Heltec Board says no GPS fix

**Comment by AHausBy** [comment]
Contacted XCGuide, looks like above Version 4.9.0 does not work with the app

**Comment by AHausBy** [comment]
XCGUIDE works with Version 4.9.0

**Comment by gereic** [comment]
Fixed in v4.11.1
