### ISSUE TITLE
No GPS 

### ISSUE THREAD

**Issue by parahooners** [gereic/GXAirCom#68]
TTGO TBEAM

Have tested GPS via Tinygps and confirm GPS module is working

no read out in info tab 

![image](https://user-images.githubusercontent.com/73525787/127771295-ed184134-a993-4f94-bdee-32a2bff12ca4.png)

**Comment by parahooners** [comment]
![image](https://user-images.githubusercontent.com/73525787/127771780-79f4b116-8252-4440-ab72-32fa51b82170.png)

**Comment by gereic** [comment]
Which Board do you have ?

**Comment by parahooners** [comment]
It's the ttgo tbeam with 3 buttons 1.1 I think 

Have tried changing the settings tab

**Comment by parahooners** [comment]
@gereic 

when trying to use the config this is the serial error im getting - the pin mapping for the board is correct for the GPS

[E][main.cpp:3758] setupUbloxConfig(): ublox: GPS not connected

**Comment by parahooners** [comment]
main.cpp

have changed the settings here 

![image](https://user-images.githubusercontent.com/73525787/127927763-749eb638-12fc-4b69-9ccd-f67806ec5110.png)

then to 

![image](https://user-images.githubusercontent.com/73525787/127928208-0cb5d95c-940d-4dae-83e0-757d06652c62.png)

is this right 

![image](https://user-images.githubusercontent.com/73525787/127928257-05ba4e79-1808-4a53-a210-5383f07d83a4.png)

still not working

**Comment by parahooners** [comment]
Had a new module delivered today have tested on 3 different ones same results - AXP192 chip is picked up but the same error occurring

**Comment by parahooners** [comment]
i can confirm that 4.8 works @gereic 

![image](https://user-images.githubusercontent.com/73525787/128405533-0ce242d5-6ed3-4ad8-9352-c58b67c16b42.png)

**Comment by gereic** [comment]
Can you post a picture of the board?
Where I can see the version and date.
I have v4.11.2 on some boards running without any problems.
Please post also the settings-page (which board selected)

**Comment by parahooners** [comment]
I got this one...


https://www.banggood.com/LILYGO-TTGO-T-Beam-ESP32-433-or-868-or-915Mhz-v0_7-WiFi-Wireless-bluetooth-Module-ESP-32-GPS-NEO-6M-SMA-LORA-32-18650-Battery-Holder-p-1320390.html?utm_source=googleshopping&utm_medium=cpc_organic&gmcCountry=GB&utm_content=minha&utm_campaign=minha-gb-en-pc&currency=GBP&cur_warehouse=UK&createTmp=1&ID=510804&utm_source=googleshopping&utm_medium=cpc_bgs&utm_content=sxxx&utm_campaign=ssc-gb-all-enw-0624-20lp&ad_id=444236244939&gclid=EAIaIQobChMI6c2gmYOd8gIVCbLtCh1JswUAEAQYBCABEgLFu_D_BwE

**Comment by gereic** [comment]
This is the V0.7, so you have to select the right Board from the list.
This Board doesn't have a axp192

**Comment by parahooners** [comment]
Yeh,

This is what's odd tho it says on the paper work it has the chip 😂


I will get some v1 boards I cheaped out on the boards

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by parahooners** [comment]
odd, so i flashed it via the firmware upgrade tab after flashing 4.8 and it blooming works.... i have no idea hahahah

**Comment by parahooners** [comment]
Manged to fix one board, unfortunately the ttgo does not have boot loader pin , shorted 3v3 and I0 to force boot loaded erased using the tool and replaced and all worked.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
