### ISSUE TITLE
New hardware support

### ISSUE THREAD

**Issue by gh4chris** [gereic/GXAirCom#69]
I'd like to learn if the new Stand alone dongle with the casing is supported?
https://www.aliexpress.com/item/4000571051141.html

**Comment by gereic** [comment]
No.
For what do you want to use the dongle?

**Comment by gh4chris** [comment]
It's meant to get used as a stand alone beacon for a "de facto TMZ" in regards of FLARM
We have this zones here where I fly and I don't want to get excluded from the spots where it is mandatory to become visible for sailplane pilots

An advantage over the SOFTRF project is the use of both 868 frequencies as far as I understood
