### ISSUE TITLE
OGN-Device ID

### ISSUE THREAD

**Issue by ParaJesper** [gereic/GXAirCom#71]
Is it possible to adjust the device ID? I have my GXairCom module connected to my phone via XC_Guide. Works great, however when using only the GXAirCom it does not show up on the tracing webpages (like gliderradar etc.).

The Device-ID has been registered with the OGN database (device-id range 083xxx). When trying the validate this ID via the app it requires an ID in the 64xxxx range. After registering a new device-id in this range I do show up. This leads me to believe that this range should be used.

Is it possible to enter this 64xxxx ID into the GXairCom?

**Comment by nepat** [comment]
The device ID for GXAircom in the 08 range is correct. This is part of the official FANET specification and was introduced 9 months ago. See https://github.com/3s1d/fanet-stm32  
It could be that third party software is not up to date with the current FANET specification.
