### ISSUE TITLE
Another baro problems

### ISSUE THREAD

**Issue by aa11bb22cc33dd44** [gereic/GXAirCom#77]
I've got two things. The first concerns the stability of pressure measurements. The first photo shows the spread of GXAirCom measurements (blue), regardless of the pressure sensor used (BME-280 or GY-86). As a result, the tablet to which I connected the GXAirCom constantly shows (and makes sounds) rising or falling, even though it is flying horizontally. On the second, instead of the GXAirCom, I connected a paraglider variometer. And here the readings are perfect. What to do to obtain such accuracy in GXAirCom?
The second problem is the number of pressure measurements per second. And so the GXAirCom makes measurements 3 times per second on average. This is definitely not enough. As a result, the measurements are delayed in relation to reality. What to do to increase the number of measurements to e.g. 10 per second?
![Screenshot_20211101-174247](https://user-images.githubusercontent.com/58511778/139715836-f503abec-e0a2-4d17-892b-5d312f8e3000.png)
![Screenshot_20211101-173614](https://user-images.githubusercontent.com/58511778/139715865-726f889f-17af-4bdc-a5df-349904f188f1.png)

**Comment by gereic** [comment]
Hi,
You are wrong and right.
The reading of the MS5611 is every 20ms
The reading of the BME280 is every 10ms
The output of the data over serial or bluetooth is every 250ms.

First it is a good idea to calibrate the GY-86-Board.
This can be done on the settings-page.
If you have done this, then you can check on the info-page, the acceleration on Z. This should be -0.05 .... 0.05

You can adjust the parameters of the Kalman-filter if you switch to the expert-settings in the settings-page.
The default-settings are:
SigmaP 0.1
SigmaA 0.6
