### ISSUE TITLE
1.7.0

### ISSUE THREAD

**Issue by nepat** [gereic/GXAirCom#8]
Did a bit of testing:
In OGN groundstation mode receive strength (db) is not transmitted to OGN
In groundstation mode targets were not showing up on the Airwhere map.

**Comment by gereic** [comment]
V1.7.1
fixed (again) bug with receive-strength (db).
You have to switch on Live-tracking service also in Ground-station-mode
So If you want that ground-station is broadcasting to Airwhere you have to switch on Live-tracking in settings.
This is essential for all live-tracking-services.
So you can decide, if your ground-station should broadcast to which service.

**Comment by nepat** [comment]
Installed, tested, works great. Thanks !
