### ISSUE TITLE
GPS is not working with latest Dev Version

### ISSUE THREAD

**Issue by parapenT1sta** [gereic/GXAirCom#82]
TTGO T-Beam T22_V1.0 / T22_V1.1

Had to roll back to master version to make it working again. With Dev version when press config GPS at the end gives me an error. Checked with LK8000 terminal and verified no GPS output was being sent. 

At the moment I'm with Master version but I can flash the Dev for version if some tests are needed.

**Comment by gereic** [comment]
Can you try it with new Dev-Version please ?

**Comment by parapenT1sta** [comment]
Same issue.

With Stable version:
![Screenshot_20211206-091434](https://user-images.githubusercontent.com/608650/144821753-3303a7b3-1677-4637-8b30-063b6e9e861e.png)

With Latest Dev
![Screenshot_20211206-092010](https://user-images.githubusercontent.com/608650/144821807-c8dc626a-07e4-4bd6-b348-63649949dfbd.png)
:

**Comment by gereic** [comment]
![image](https://user-images.githubusercontent.com/57770169/144857948-7b0bb84d-461d-4e5c-9502-43697dc2309b.png)
 I have checked that and it works.
Is the Board connected via bluetooth or serial ?

**Comment by parapenT1sta** [comment]
When I press Config GPS it fails.
![Screenshot_20211206-150718](https://user-images.githubusercontent.com/608650/144870922-2e0da6ae-318e-463c-b670-40044b157475.png)

![Screenshot_20211206-150723](https://user-images.githubusercontent.com/608650/144870947-93b4b382-f3c5-4fe7-8471-f4e95978960a.png)

**Comment by gereic** [comment]
Please download again the firmware directly from git and try again.
Maybe you have an old dev-version.
Make a screenshot from info-screen.
The compile-date should be from today.

**Comment by parapenT1sta** [comment]
I didn't update after your message because I already had the latest version, this is the firmware I am using:

![Inked1](https://user-images.githubusercontent.com/608650/144893323-815e63f8-6d04-4f6f-a221-50e34b972a83.jpg)

**Comment by parapenT1sta** [comment]
Just ignore my "issue", if it is working for you I might be doing something wrong.
I will keep with 4.12 master version that is working perfectly fine for me.

**Comment by parapenT1sta** [comment]
@gereic I just wanted to leave my latest feedback, I went back on Dev releases to find which one worked for me, and I found the latest DEV 0.13 that works for me! 🥇
This build works perfectly fine with GPS, all releases after I only get the $PFLAU sentence: https://github.com/gereic/GXAirCom/commit/a0223933aea7dcdb497144d7431df5765e0b6f79#diff-97c8e95a046a07cbeb99e61fb3ae6d9665d265955d6fab5206f4c52e8180cdfb

**Comment by parapenT1sta** [comment]
Found the issue, before was working even with the wrong board selected. Now with the changes the correct board must be selected. Sorry !!

**Comment by gereic** [comment]
That is good to hear.
Thanks for your response

**Comment by parapenT1sta** [comment]
@gereic Thank you for the support.
