### ISSUE TITLE
Version 4.13 double definition of GPIO34

### ISSUE THREAD

**Issue by wielandsteffan** [gereic/GXAirCom#84]
I have a Heltec Board for flying. After installing V4.13 there ist no GPS data anymore. In Serial output GPSRX changed from GPIO12 to GPIO34 in the new Version. But i found that there is a double definition of GPIO34 in main.cpp   

PinGPSRX = 34;
PinADCVoltage = 34;

best regards Wieland

**Comment by parapenT1sta** [comment]
I had a similar issue regarding GPS not working but I found out in my case that before I was able to use it even when the wrong board was selected but it seems that is not your case. https://github.com/gereic/GXAirCom/issues/82

Maybe @gereic can assist you better.

**Comment by wielandsteffan** [comment]
When i change definition of GPSRX to GPIO12 in main.cpp and recompile V4.13 then it works as before.

**Comment by parapenT1sta** [comment]
Submit the change here on Github so can be reviewed by @gereic

**Comment by gereic** [comment]
@wielandsteffan Can you try latest dev-Version please ?
