### ISSUE TITLE
Error in main.h: Pin definition of e-ink for TTGO-TBeam V1.0 / V1.1 

### ISSUE THREAD

**Issue by mwesterm** [gereic/GXAirCom#93]
main.h

Line 28: should be "RST 0"
Line 32: should be "CLK 4"

Costs me 2 h to find the reason why my e-ink doesn't work

**Comment by gereic** [comment]
Sorry, I will remove that.
The PIN-Definition is in "/bin/readme.txt".
So no need to look to source.
