### ISSUE TITLE
Wrong position reported via legacy (FLARM)

### ISSUE THREAD

**Issue by sbishop61** [gereic/GXAirCom#95]
I have a Heltec as a ground station and a T-Beam v0.7 set to TX FANET and LEGACY.
When I look at the groundstation webpage the position reported is very different when received by FANET or legacy. FANET is correct, legacy is somewhere in the South Atlantic:

`Stephen Bishop [088E6C]	UNKNOWN	-0.795818	-6.710405	walking		0m	0.0km/h	0.0m/s	0°	-28dB	0s	LEGACY

Stephen Bishop [088E6C]	UNKNOWN	46.180397	6.711349	walking		0m	0.0km/h	0.0m/s	0°	-36dB	0s	FANET`

If I click on the Legacy position it shows on the map in the South Atlantic.

I have both configured for  airwhere live-tracking but nothing appears of the Airwhere tracking map. How can I check what is happening?

Thanks

**Comment by gereic** [comment]
I think the problem is the GPS-Position on the ground-station.
Fanet is sending the position in absolut-cooridnates.
For Legacy, the cooridnates have to be decoded with current position.
So, if Position in settings is zero or wrong, you get the wrong position for Legacy-messages.
